apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cm.yaml
- helmrelease.yaml
- langgraph-ui-dashboard-cm.yaml
- langgraph-postinstall-rbac.yaml
- langgraph-postinstall-job.yaml
---
