# Bloodhound config for Kueue 0.18.0
k8s_versions:
  - 1.34.0

strict: false

skip_types: []

additional_crds: []

substitution_vars:
  releaseNamespace: kommander
  releaseName: kueue
  workspaceNamespace: workspace
  appVersion: "0.18.0"
