apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${releaseNamespace}
configMapGenerator:
  - name: ${releaseName}-${appVersion}-metrics-exporter-config
    files:
      - config.json
generatorOptions:
  disableNameSuffixHash: true
