apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cm.yaml
  - helmrelease.yaml
  - demo-full-rag-ui-dashboard-cm.yaml
  - demo-full-rag-postinstall-rbac.yaml
  - demo-full-rag-postinstall-job.yaml
---
