applications/amd-device-metrics-exporter:
- changed-files:
  - any-glob-to-any-file:
    - applications/amd-device-metrics-exporter/**
applications/amd-gpu-operator:
- changed-files:
  - any-glob-to-any-file:
    - applications/amd-gpu-operator/**
applications/amd-network-operator:
- changed-files:
  - any-glob-to-any-file:
    - applications/amd-network-operator/**