# Source for check-versions: Helm repo (pulled and pushed to OCI during add-app)
helmrepo: weaviate/weaviate
helmrepoUrl: https://weaviate.github.io/weaviate-helm/
ocipush: oci://ghcr.io/deepak-muley/charts
