apiVersion: v1
data:
  values.yaml: |
    operator:
      image:
        tag: "1.1.1"
    webhook:
      image:
        tag: "1.1.1"
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-defaults
  namespace: ${releaseNamespace}
---
