# Kubernetes versions
# (e.g. 1.33.0 - has to match versions in https://github.com/yannh/kubernetes-json-schema)
k8s_versions:
  - 1.34.1
  - 1.35.2
  - 1.36.1

# use strict validation (reject unknown fields in resources)
strict: true

# types to be skipped (e.g. certmanager.k8s.io/v1, or certmanager.k8s.io/v1/Certificate)
skip_types:
  - networking.istio.io/v1alpha3/DestinationRule
  - networking.istio.io/v1alpha3/VirtualService
  - networking.istio.io/v1alpha3/EnvoyFilter
  - security.istio.io/v1beta1/AuthorizationPolicy
  - metacontroller.k8s.io/v1alpha1/DecoratorController
