apiVersion: v1
data:
  values.yaml: |
    coder:
      env:
        - name: CODER_ACCESS_URL
          value: ${coderAccessURL}
      service:
        type: ClusterIP
      ingress:
        enable: false
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-defaults
  namespace: ${releaseNamespace}
---
