apiVersion: v1
data:
  values.yaml: |
    tls:
      redirectHttpToHttps: true
    dashboard:
      namespace: ${workspaceNamespace}
      configMapName: ${releaseName}-ui
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-defaults
  namespace: ${releaseNamespace}
---
