# Source for check-versions: Helm repo (pull and push to OCI via publish-chart-oci workflow)
helmrepo: coder-v2
helmrepoUrl: https://helm.coder.com/v2
ocipush: oci://ghcr.io/nutanix-cloud-native/charts/coder
