apiVersion: v1
data:
  values.yaml: |
    fullnameOverride: "kagent"
    providers:
      default: ollama
      ollama:
        config:
          host: "ollama-ollama.ollama.svc.cluster.local:11434"
        model: "llama3.2"
        provider: "Ollama"
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-defaults
  namespace: ${releaseNamespace}
---
