apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${releaseName}-chart
  namespace: ${releaseNamespace}
spec:
  type: oci
  interval: 6h0m0s
  url: oci://ghcr.io/kagent-dev/kagent/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kagent
      version: "0.7.13"
      sourceRef:
        kind: HelmRepository
        name: ${releaseName}-chart
        namespace: ${releaseNamespace}
  dependsOn:
  - name: ${releaseName}-crds
    namespace: ${releaseNamespace}
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 30
  interval: 15s
  targetNamespace: kagent
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  valuesFrom:
  - kind: ConfigMap
    name: ${releaseName}-${appVersion}-defaults
  values:
    fullnameOverride: "kagent"
---
