apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cm.yaml
- crds-helmrelease.yaml
- helmrelease.yaml
- kagent-ui-dashboard-cm.yaml
- kagent-postinstall-rbac.yaml
- kagent-postinstall-job.yaml
---
