apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cm.yaml
  - helmrelease.yaml
  - demo-connector-ui-dashboard-cm.yaml
  - demo-connector-postinstall-rbac.yaml
  - demo-connector-postinstall-job.yaml
---
