k8s_versions:
  - 1.34.0

# Substitution vars for validation (nkp validate uses these)
substitution_vars:
  releaseNamespace: kommander
  releaseName: nvidia-nim
  appVersion: "1.0.3"
  workspaceNamespace: workspace
