apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${releaseName}-chart
  namespace: ${releaseNamespace}
spec:
  interval: 6h0m0s
  ref:
    tag: 1.7.0
  url: oci://ghcr.io/nutanix-cloud-native/charts/ray-cluster
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ray-cluster
  namespace: ${releaseNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ${releaseName}-chart
    namespace: ${releaseNamespace}
  install:
    createNamespace: true
    remediation:
      retries: 30
  interval: 15s
  targetNamespace: kuberay
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
  - kind: ConfigMap
    name: ${releaseName}-config-defaults
---
