apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cm.yaml
- helmrelease.yaml
- openwebui-ui-dashboard-cm.yaml
- traefik-ingressroute.yaml
- openwebui-postinstall-rbac.yaml
- openwebui-postinstall-job.yaml
---
