# Stage 03 — Keycloak realm, clients, users, and role configuration
#
# This script implements the configuration portions of installer step 7:
# - 7b: create the `airm` realm, OIDC clients, and service-account role mapping.
# - 7b2: create a permanent `kcadmin` user for the Keycloak admin console.
# - 7b3: create the default AIRM user and grant Platform Administrator.
# Keycloak installation and step 7c's HTTPRoute are declarative resources in
# resources.yaml; they are not created by this script.
#
# The Job authenticates to Keycloak's internal Service with the bootstrap admin
# password generated by the Helm chart. It then reconciles:
# - confidential admin client `${KEYCLOAK_CLIENT_ID}` and its service account;
# - `airm-ui` client using the same authoritative client secret;
# - `realm-admin` and `Platform Administrator` role assignments;
# - permanent `kcadmin` in the master realm;
# - the default AIRM user and non-temporary password;
# - Kubernetes Secret copies consumed by the AIRM charts.
#
# Differences from the original installer step 7 configuration:
# 1. Calls go directly to the stable in-cluster Keycloak Service instead of
#    `kubectl exec` into the assumed `keycloak-0` pod.
# 2. Existing clients and users are read and updated with PUT, not only created
#    with POST-and-ignore-conflict. This repairs configuration drift on retry.
# 3. The actual Keycloak client secret is treated as authoritative and synced
#    back to both Kubernetes Secret shapes created by stage 01.
# 4. An existing `keycloak-kcadmin` password is preserved. The installer
#    generated and reset a random password whenever step 7 was rerun.
# 5. The default user's profile, password, and empty `requiredActions` are
#    reconciled even when that user already exists; the installer mostly
#    skipped an existing user.
# 6. Realm/client/user/role state and a real password-grant login are verified
#    at the end. Failures stop Flux instead of being hidden by `|| true`.
# 7. Random fallback generation uses `/dev/urandom` + `od` rather than openssl
#    because this runs in the pinned cluster utility image.
#
# Requests accepting HTTP 409 are limited to idempotent create/role-assignment
# operations. Other non-2xx responses fail the Job so later AIRM stages cannot
# start with incomplete authentication configuration.

log() {
  printf '%s\n' "==> $*"
}

fail() {
  printf '%s\n' "ERROR: $*" >&2
  exit 1
}

rand_hex() {
  od -An -N "$1" -tx1 /dev/urandom | tr -d ' \n'
}

command -v curl >/dev/null || fail "curl is unavailable"
command -v jq >/dev/null || fail "jq is unavailable"
command -v kubectl >/dev/null || fail "kubectl is unavailable"

KEYCLOAK_NAMESPACE="$${KEYCLOAK_NAMESPACE:?KEYCLOAK_NAMESPACE is required}"
AIRM_NAMESPACE="$${AIRM_NAMESPACE:?AIRM_NAMESPACE is required}"
KEYCLOAK_CLIENT_ID="$${KEYCLOAK_CLIENT_ID:?KEYCLOAK_CLIENT_ID is required}"
KC_URL="http://keycloak.$${KEYCLOAK_NAMESPACE}.svc.cluster.local"

log "Waiting for Keycloak"
for attempt in $(seq 1 120); do
  if curl -fsS "$${KC_URL}/realms/master" >/dev/null 2>&1; then
    break
  fi
  [ "$attempt" -lt 120 ] || fail "Keycloak did not become ready"
  sleep 5
done

KC_ADMIN_PASS="$(kubectl get secret keycloak -n "$KEYCLOAK_NAMESPACE" \
  -o jsonpath='{.data.admin-password}' | base64 -d)"
[ -n "$KC_ADMIN_PASS" ] || fail "Keycloak admin password is unavailable"

TOKEN=""
for attempt in $(seq 1 12); do
  TOKEN="$(curl -fsS -X POST \
    "$${KC_URL}/realms/master/protocol/openid-connect/token" \
    --data-urlencode client_id=admin-cli \
    --data-urlencode username=admin \
    --data-urlencode "password=$KC_ADMIN_PASS" \
    --data-urlencode grant_type=password 2>/dev/null \
    | jq -r '.access_token // empty')"
  [ -n "$TOKEN" ] && break
  [ "$attempt" -lt 12 ] || fail "failed to obtain Keycloak admin token"
  sleep 5
done

kc_get() {
  curl -fsS "$${KC_URL}$1" -H "Authorization: Bearer $TOKEN"
}

kc_write() {
  method="$1"
  path="$2"
  data="$3"
  curl -fsS -X "$method" "$${KC_URL}$path" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$data"
}

kc_write_idempotent() {
  method="$1"
  path="$2"
  data="$3"
  response_file="$(mktemp)"
  status="$(curl -sS -o "$response_file" -w '%{http_code}' \
    -X "$method" "$${KC_URL}$path" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d "$data")" || {
      rm -f "$response_file"
      fail "Keycloak API request failed: $method $path"
    }
  case "$status" in
    2??|409)
      rm -f "$response_file"
      ;;
    *)
      cat "$response_file" >&2
      rm -f "$response_file"
      fail "Keycloak API request failed ($status): $method $path"
      ;;
  esac
}

log "Ensuring AIRM realm"
kc_write_idempotent POST /admin/realms '{"realm":"airm","enabled":true}'

UI_CLIENT_SECRET="$(kubectl get secret airm-keycloak-ui-creds \
  -n "$AIRM_NAMESPACE" -o jsonpath='{.data.KEYCLOAK_SECRET}' | base64 -d)"
[ -n "$UI_CLIENT_SECRET" ] || fail "airm-keycloak-ui-creds is empty"

ADMIN_INTERNAL_ID="$(kc_get \
  "/admin/realms/airm/clients?clientId=$KEYCLOAK_CLIENT_ID" \
  | jq -r '.[0].id // empty')"
if [ -z "$ADMIN_INTERNAL_ID" ]; then
  log "Creating AIRM admin client"
  kc_write_idempotent POST /admin/realms/airm/clients "{
    \"clientId\":\"$KEYCLOAK_CLIENT_ID\",
    \"enabled\":true,
    \"protocol\":\"openid-connect\",
    \"publicClient\":false,
    \"serviceAccountsEnabled\":true,
    \"directAccessGrantsEnabled\":true,
    \"standardFlowEnabled\":true,
    \"secret\":\"$UI_CLIENT_SECRET\",
    \"redirectUris\":[\"*\"],
    \"webOrigins\":[\"*\"]
  }"
  ADMIN_INTERNAL_ID="$(kc_get \
    "/admin/realms/airm/clients?clientId=$KEYCLOAK_CLIENT_ID" \
    | jq -r '.[0].id // empty')"
fi
[ -n "$ADMIN_INTERNAL_ID" ] || fail "AIRM admin client was not created"

ADMIN_CLIENT_JSON="$(kc_get \
  "/admin/realms/airm/clients/$ADMIN_INTERNAL_ID" \
  | jq --arg client_id "$KEYCLOAK_CLIENT_ID" '
    .clientId = $client_id
    | .enabled = true
    | .protocol = "openid-connect"
    | .publicClient = false
    | .serviceAccountsEnabled = true
    | .directAccessGrantsEnabled = true
    | .standardFlowEnabled = true
    | .redirectUris = ["*"]
    | .webOrigins = ["*"]
  ')"
kc_write PUT "/admin/realms/airm/clients/$ADMIN_INTERNAL_ID" \
  "$ADMIN_CLIENT_JSON" >/dev/null

KC_CLIENT_SECRET="$(kc_get \
  "/admin/realms/airm/clients/$ADMIN_INTERNAL_ID/client-secret" \
  | jq -r '.value // empty')"
[ -n "$KC_CLIENT_SECRET" ] || fail "Keycloak client secret is unavailable"

log "Synchronizing Keycloak client Secrets"
kubectl create secret generic airm-keycloak-admin-client \
  -n "$AIRM_NAMESPACE" \
  --from-literal=client-id="$KEYCLOAK_CLIENT_ID" \
  --from-literal=client-secret="$KC_CLIENT_SECRET" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic airm-keycloak-ui-creds \
  -n "$AIRM_NAMESPACE" \
  --from-literal=KEYCLOAK_SECRET="$KC_CLIENT_SECRET" \
  --dry-run=client -o yaml | kubectl apply -f -

REALM_MGMT_ID="$(kc_get \
  '/admin/realms/airm/clients?clientId=realm-management' \
  | jq -r '.[0].id // empty')"
SA_USER_ID="$(kc_get \
  "/admin/realms/airm/clients/$ADMIN_INTERNAL_ID/service-account-user" \
  | jq -r '.id // empty')"
[ -n "$REALM_MGMT_ID" ] || fail "realm-management client is unavailable"
[ -n "$SA_USER_ID" ] || fail "AIRM client service account is unavailable"
REALM_ADMIN_ROLE="$(kc_get \
  "/admin/realms/airm/clients/$REALM_MGMT_ID/roles/realm-admin")"
kc_write_idempotent POST \
  "/admin/realms/airm/users/$SA_USER_ID/role-mappings/clients/$REALM_MGMT_ID" \
  "[$REALM_ADMIN_ROLE]"

UI_INTERNAL_ID="$(kc_get '/admin/realms/airm/clients?clientId=airm-ui' \
  | jq -r '.[0].id // empty')"
if [ -z "$UI_INTERNAL_ID" ]; then
  log "Creating AIRM UI client"
  kc_write_idempotent POST /admin/realms/airm/clients "{
    \"clientId\":\"airm-ui\",
    \"enabled\":true,
    \"protocol\":\"openid-connect\",
    \"publicClient\":false,
    \"directAccessGrantsEnabled\":true,
    \"secret\":\"$KC_CLIENT_SECRET\",
    \"redirectUris\":[\"*\"],
    \"webOrigins\":[\"*\"]
  }"
  UI_INTERNAL_ID="$(kc_get '/admin/realms/airm/clients?clientId=airm-ui' \
    | jq -r '.[0].id // empty')"
fi
[ -n "$UI_INTERNAL_ID" ] || fail "AIRM UI client was not created"
UI_CLIENT_JSON="$(kc_get "/admin/realms/airm/clients/$UI_INTERNAL_ID" \
  | jq --arg secret "$KC_CLIENT_SECRET" '
    .clientId = "airm-ui"
    | .enabled = true
    | .protocol = "openid-connect"
    | .publicClient = false
    | .directAccessGrantsEnabled = true
    | .secret = $secret
    | .redirectUris = ["*"]
    | .webOrigins = ["*"]
  ')"
kc_write PUT "/admin/realms/airm/clients/$UI_INTERNAL_ID" \
  "$UI_CLIENT_JSON" >/dev/null

KCADMIN_PASS="$(kubectl get secret keycloak-kcadmin \
  -n "$KEYCLOAK_NAMESPACE" -o jsonpath='{.data.password}' 2>/dev/null \
  | base64 -d 2>/dev/null || true)"
[ -n "$KCADMIN_PASS" ] || KCADMIN_PASS="$(rand_hex 12)"
KCADMIN_ID="$(kc_get \
  '/admin/realms/master/users?username=kcadmin&exact=true' \
  | jq -r '.[0].id // empty')"
if [ -z "$KCADMIN_ID" ]; then
  log "Creating permanent Keycloak administrator"
  kc_write_idempotent POST /admin/realms/master/users "{
    \"username\":\"kcadmin\",
    \"enabled\":true,
    \"emailVerified\":true
  }"
  KCADMIN_ID="$(kc_get \
    '/admin/realms/master/users?username=kcadmin&exact=true' \
    | jq -r '.[0].id // empty')"
fi
[ -n "$KCADMIN_ID" ] || fail "kcadmin user was not created"
kc_write PUT \
  "/admin/realms/master/users/$KCADMIN_ID/reset-password" \
  "{\"type\":\"password\",\"value\":\"$KCADMIN_PASS\",\"temporary\":false}" \
  >/dev/null
MASTER_ADMIN_ROLE="$(kc_get /admin/realms/master/roles/admin)"
kc_write_idempotent POST \
  "/admin/realms/master/users/$KCADMIN_ID/role-mappings/realm" \
  "[$MASTER_ADMIN_ROLE]"
kubectl create secret generic keycloak-kcadmin \
  -n "$KEYCLOAK_NAMESPACE" \
  --from-literal=username=kcadmin \
  --from-literal=password="$KCADMIN_PASS" \
  --dry-run=client -o yaml | kubectl apply -f -

AIRM_USER_EMAIL="$(kubectl get secret airm-user-credentials \
  -n "$AIRM_NAMESPACE" -o jsonpath='{.data.USER_EMAIL}' | base64 -d)"
AIRM_USER_PASS="$(kubectl get secret airm-user-credentials \
  -n "$AIRM_NAMESPACE" -o jsonpath='{.data.USER_PASSWORD}' | base64 -d)"
[ -n "$AIRM_USER_EMAIL" ] || fail "AIRM user email is unavailable"
[ -n "$AIRM_USER_PASS" ] || fail "AIRM user password is unavailable"
AIRM_USER_QUERY="$(printf '%s' "$AIRM_USER_EMAIL" | jq -sRr @uri)"
AIRM_USER_ID="$(kc_get \
  "/admin/realms/airm/users?username=$AIRM_USER_QUERY&exact=true" \
  | jq -r '.[0].id // empty')"
if [ -z "$AIRM_USER_ID" ]; then
  log "Creating default AIRM user"
  kc_write_idempotent POST /admin/realms/airm/users "{
    \"username\":\"$AIRM_USER_EMAIL\",
    \"email\":\"$AIRM_USER_EMAIL\",
    \"firstName\":\"AIRM\",
    \"lastName\":\"User\",
    \"enabled\":true,
    \"emailVerified\":true,
    \"requiredActions\":[],
    \"credentials\":[{
      \"type\":\"password\",
      \"value\":\"$AIRM_USER_PASS\",
      \"temporary\":false
    }]
  }"
  AIRM_USER_ID="$(kc_get \
    "/admin/realms/airm/users?username=$AIRM_USER_QUERY&exact=true" \
    | jq -r '.[0].id // empty')"
fi
[ -n "$AIRM_USER_ID" ] || fail "default AIRM user was not created"
AIRM_USER_JSON="$(kc_get "/admin/realms/airm/users/$AIRM_USER_ID" \
  | jq --arg email "$AIRM_USER_EMAIL" '
    .username = $email
    | .email = $email
    | .firstName = "AIRM"
    | .lastName = "User"
    | .enabled = true
    | .emailVerified = true
    | .requiredActions = []
  ')"
kc_write_idempotent PUT \
  "/admin/realms/airm/users/$AIRM_USER_ID" "$AIRM_USER_JSON"
kc_write_idempotent PUT \
  "/admin/realms/airm/users/$AIRM_USER_ID/reset-password" \
  "{
    \"type\":\"password\",
    \"value\":\"$AIRM_USER_PASS\",
    \"temporary\":false
  }"

kc_write_idempotent POST /admin/realms/airm/roles \
  '{"name":"Platform Administrator","description":"Full AIRM administrative access"}'
PA_ROLE="$(kc_get \
  '/admin/realms/airm/roles/Platform%20Administrator')"
kc_write_idempotent POST \
  "/admin/realms/airm/users/$AIRM_USER_ID/role-mappings/realm" \
  "[$PA_ROLE]"
kc_write_idempotent POST \
  "/admin/realms/airm/users/$SA_USER_ID/role-mappings/realm" \
  "[$PA_ROLE]"

log "Verifying Keycloak configuration"
[ "$(kc_get /admin/realms/airm | jq -r '.realm')" = "airm" ] \
  || fail "AIRM realm verification failed"
[ -n "$(kc_get "/admin/realms/airm/clients?clientId=$KEYCLOAK_CLIENT_ID" \
  | jq -r '.[0].id // empty')" ] || fail "AIRM client verification failed"
[ -n "$(kc_get \
  "/admin/realms/airm/users?username=$AIRM_USER_QUERY&exact=true" \
  | jq -r '.[0].id // empty')" ] || fail "AIRM user verification failed"
[ "$(kc_get "/admin/realms/airm/users/$AIRM_USER_ID" \
  | jq -r '.requiredActions | length')" = "0" ] \
  || fail "AIRM user still has required account actions"
[ "$(kc_get \
  "/admin/realms/airm/users/$AIRM_USER_ID/role-mappings/realm" \
  | jq -r 'any(.[]; .name == "Platform Administrator")')" = "true" ] \
  || fail "Platform Administrator user assignment verification failed"
[ "$(kc_get \
  "/admin/realms/airm/users/$SA_USER_ID/role-mappings/realm" \
  | jq -r 'any(.[]; .name == "Platform Administrator")')" = "true" ] \
  || fail "Platform Administrator service-account assignment verification failed"

log "Verifying default AIRM user password grant"
AIRM_USER_TOKEN="$(curl -fsS -X POST \
  "$KC_URL/realms/airm/protocol/openid-connect/token" \
  --data-urlencode "client_id=$KEYCLOAK_CLIENT_ID" \
  --data-urlencode "username=$AIRM_USER_EMAIL" \
  --data-urlencode "password=$AIRM_USER_PASS" \
  --data-urlencode grant_type=password \
  --data-urlencode "client_secret=$KC_CLIENT_SECRET" \
  | jq -r '.access_token // empty')"
[ -n "$AIRM_USER_TOKEN" ] \
  || fail "default AIRM user password grant verification failed"

log "AIRM Keycloak configuration completed"
