apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${releaseName}-postinstall
  namespace: ${workspaceNamespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${releaseName}-postinstall
  namespace: ${workspaceNamespace}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]
    resourceNames: ["${releaseName}-ui"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${releaseName}-postinstall
  namespace: ${workspaceNamespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${releaseName}-postinstall
subjects:
  - kind: ServiceAccount
    name: ${releaseName}-postinstall
    namespace: ${workspaceNamespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${releaseName}-postinstall-ingress
  namespace: open-webui
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${releaseName}-postinstall-ingress
  namespace: open-webui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${releaseName}-postinstall-ingress
subjects:
  - kind: ServiceAccount
    name: ${releaseName}-postinstall
    namespace: ${workspaceNamespace}
---
