apiVersion: v1
data:
  values.yaml: |
    image:
      repository: nvcr.io/nim/meta/llama3-8b-instruct
      tag: "1.0.3"
    model:
      ngcAPISecret: ngc-api
      name: meta/llama3-8b-instruct
    persistence:
      enabled: true
      size: 50Gi
    imagePullSecrets:
      - name: ngc-secret
    resources:
      limits:
        nvidia.com/gpu: 1
kind: ConfigMap
metadata:
  name: ${releaseName}-${appVersion}-defaults
  namespace: ${releaseNamespace}
---
