# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Publish Chart to GHCR

on:
  workflow_dispatch:
    inputs:
      chart_repo:
        description: 'Source Helm repository URL (e.g., https://weaviate.github.io/weaviate-helm/)'
        type: string
        required: true
      repo_name:
        description: 'Helm repo alias for helm repo add / helm pull (e.g., weaviate, ollama-helm)'
        type: string
        required: true
      chart_name:
        description: 'Helm chart name in the repo (e.g., weaviate, ollama)'
        type: string
        required: true
      chart_version:
        description: 'Helm chart version'
        type: string
        required: true
      target_oci_registry:
        description: 'Target OCI registry (e.g., oci://ghcr.io/nutanix-cloud-native/charts)'
        type: string
        required: false
        default: 'oci://ghcr.io/nutanix-cloud-native/charts'

jobs:
  push-chart:
    name: Publish Chart to GHCR
    runs-on:
      - self-hosted-nutanix-medium
    env:
      TARGET_OCI_REGISTRY: ${{ github.event.inputs.target_oci_registry }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Helm chart
        run: |
          set -euo pipefail
          helm repo add "${{ github.event.inputs.repo_name }}" "${{ github.event.inputs.chart_repo }}"
          helm repo update
          helm pull ${{ github.event.inputs.repo_name }}/${{ github.event.inputs.chart_name }} --version ${{ github.event.inputs.chart_version }}

      - name: Push chart to GHCR
        run: |
          helm push ${{ github.event.inputs.chart_name }}-${{ github.event.inputs.chart_version }}.tgz ${{ env.TARGET_OCI_REGISTRY }}
